import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hello World",
  description: "Generated by create next app",
};

export interface RootLayoutProps extends React.PropsWithChildren {}

export default function RootLayout(props: RootLayoutProps) {
  const { children } = props;
  return (
    <html lang="en">
      <body className={""}>{children}</body>
    </html>
  );
}
