export const SOCKET_EVENTS = {
  REPORT_BIN_FULL: "BIN.REPORT_FULL",
  BIN_REPORTS: "BIN.NUM_REPORTS",
  BIN_DISPOSAL: "BIN.ON_DISPOSAL",
  BIN_EMPTY: "BIN.ON_EMPTY",
  DISPOSER_LOGIN: "DISPOSER_LOGIN",
  USER_LOGIN: "USER_LOGIN",
  LOGOUT: "LOGOUT",
  DISCONNECT: "disconnect",
  CONNECT: "connect",
} as const;
